<a href="https://colab.research.google.com/github/warigiasue89/Refresher/blob/master/Refresher.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
learning = list(['orange','pineapple','mango'])
learning

['orange', 'pineapple', 'mango']

In [ ]:
iteration = 2
for i in learning:
  iteration +=2
  print('iteration number:', iteration)
  print (i)
print ('is not in the for loop')

iteration number: 4
orange
iteration number: 6
pineapple
iteration number: 8
mango
is not in the for loop


In [ ]:
for fruits in learning:
  print (fruits)

orange
pineapple
mango


In [ ]:
countries= ['Crotia', 'USA', 'Argentina', 'France', 'Brazil', 'Japan','Vietnam']
countries

['Crotia', 'USA', 'Argentina', 'France', 'Brazil', 'Japan', 'Vietnam']

In [ ]:
for index in range(len(countries)):
  print(index)
  print(countries[index])

0
Crotia
1
USA
2
Argentina
3
France
4
Brazil
5
Japan
6
Vietnam


In [ ]:
countries= ['Crotia', 'USA', 'Argentina', 'France', 'Brazil', 'Japan','Vietnam']
cities = ['Zagreb', 'District of Columbia', 'Buenos Aires', 'Paris', 'Rio de Janeiro', 'Tokyo', 'Hanoi']

In [ ]:
for index in range(len(countries)):
  print(cities[index],",", countries[index])

Zagreb , Crotia
District of Columbia , USA
Buenos Aires , Argentina
Paris , France
Rio de Janeiro , Brazil
Tokyo , Japan
Hanoi , Vietnam


In [ ]:
# for index in range(8):
#    print(cities[index],",", countries[index])

Zagreb , Crotia
District of Columbia , USA
Buenos Aires , Argentina
Paris , France
Rio de Janeiro , Brazil
Tokyo , Japan
Hanoi , Vietnam


IndexError: list index out of range

In [ ]:
range(len(countries))

range(0, 7)

In [ ]:
list (range(len(countries)))

[0, 1, 2, 3, 4, 5, 6]

In [ ]:
for index in list(range(len(countries))):
  print(cities[index],",",countries[index])


Zagreb , Crotia
District of Columbia , USA
Buenos Aires , Argentina
Paris , France
Rio de Janeiro , Brazil
Tokyo , Japan
Hanoi , Vietnam


In [ ]:
countries.append ('Kenya')
cities.append ('Nairobi')
for index in list(range(len(countries))):
  print(cities[index],",",countries[index])

Zagreb , Crotia
District of Columbia , USA
Buenos Aires , Argentina
Paris , France
Rio de Janeiro , Brazil
Tokyo , Japan
Hanoi , Vietnam
Nairobi , Kenya


In [ ]:
countries.reverse()


In [ ]:
countries

['Kenya', 'Vietnam', 'Japan', 'Brazil', 'France', 'Argentina', 'USA', 'Crotia']

In [ ]:
different_elements = ['Susan', ['shopping', 10, 'Saturday'],{'This is the key': '10'}]
different_elements

['Susan', ['shopping', 10, 'Saturday'], {'This is the key': '10'}]

In [ ]:
for element in different_elements:
  print(element)

Susan
['shopping', 10, 'Saturday']
{'This is the key': '10'}


In [ ]:
example_of_dictionary = {'first_name': 'mia', 'last_name':'Kebaso','age':27}
example_of_dictionary

{'first_name': 'mia', 'last_name': 'Kebaso', 'age': 27}

In [ ]:
example_of_dictionary.items()

dict_items([('first_name', 'mia'), ('last_name', 'Kebaso'), ('age', 27)])

In [ ]:
example_of_dictionary.keys()

dict_keys(['first_name', 'last_name', 'age'])

In [ ]:
example_of_dictionary.values()

dict_values(['mia', 'Kebaso', 27])

In [ ]:
for key, value in example_of_dictionary.items():
  print('this is the key:',key)
  print('this is the value:', value,'\n')

this is the key: first_name
this is the value: mia 

this is the key: last_name
this is the value: Kebaso 

this is the key: age
this is the value: 27 



In [ ]:
# last_name =''
# first_name = ''
for key,value in example_of_dictionary.items():
  if key == 'first_name':
    first_name = value.upper()
  if key == 'last_name':
    last_name = value.lower()
print(first_name, last_name)


MIA kebaso


WHILE LOOPS

How to continue and break the loop

In [ ]:
water_cans = 10
cans_carried= 0

for water_can in range(water_cans):
  print('We have carried')
  cans_carried +=1
  print(f'{cans_carried} can')
  # print(cans_carried)
  # print(cans_carried,'cans so far')


We have carried
1 can
We have carried
2 can
We have carried
3 can
We have carried
4 can
We have carried
5 can
We have carried
6 can
We have carried
7 can
We have carried
8 can
We have carried
9 can
We have carried
10 can


FUNCTIONS

In [ ]:
def greet_people():
  print('Habari')

In [ ]:
greet_people()

Habari


In [ ]:
def calc (a,b):
  return(a*b)

In [ ]:
calc(2,5)

10

In [ ]:
new_interns = ['Kelly', 'Fiona' , 'Susan']


In [ ]:
# def greet_people(name):
#   print('Habari', name)

In [ ]:
# Defining a  function
def greet_people():
  welcome_message= []
  for name in new_interns:
    welcome_message.append('Habari' ' ' + name)
  return welcome_message

In [ ]:
#Executing the function
greet_people()

['Habari Kelly', 'Habari Fiona', 'Habari Susan']

In [ ]:
travel_destination = ['argentina', 'mexico', 'italy', 'finland', 'canada', 'croatia']


In [ ]:
def number_of_destination():
  return len(travel_destination)

In [ ]:
number_of_destination()

6

In [ ]:
def next_up():
  return travel_destination[0]

In [ ]:
next_up()

'argentina'

In [ ]:
def favourite_destination():
  return('Madagascar')

In [ ]:
favourite_destination()

'Madagascar'

In [ ]:
def add_favourite_destination ():
  travel_destination.append(favourite_destination())
  return travel_destination[-1]

In [ ]:
add_favourite_destination()

'Madagascar'

In [ ]:
def capitalize_countries():
  for index in range(len(travel_destination)):
    travel_destination[index] = travel_destination[index].capitalize()
  return travel_destination

In [ ]:
capitalize_countries()

['Argentina', 'Mexico', 'Italy', 'Finland', 'Canada', 'Croatia', 'Madagascar']

In [ ]:
def meet(name):
  print('Jina langu ni' + ' ' + name)

In [ ]:
meet('Mylo')

Jina langu ni Mylo


In [ ]:
def find_the_mean(list_of_numbers):
  n= len(list_of_numbers)
  summation = sum(list_of_numbers)
  mean = summation/n
  return mean


In [ ]:
find_the_mean([1,2,3,4,5,6,7,8,9,10])

5.5

In [ ]:
area_one_pops = [10453, 12383, 8034, 800835, 76434, 32394]
find_the_mean(area_one_pops)

156755.5

In [ ]:
area_two_pops = [43845, 54930, 59354, 96403, 73492, 729320]
find_the_mean(area_two_pops)

176224.0

In [ ]:
def find_largest_pop(area_one_pops,area_two_pops):
  mean_one = find_the_mean(area_one_pops)
def find_largest_pop(area_one_pops,area_two_pops):
  mean_one = find_the_mean(area_one_pops)
  mean_two = find_the_mean(area_two_pops)
  if mean_one > mean_two:
    return ('Population One is larger', area_one_pops)
  else:
    return ('Population Two is larger', area_two_pops)

In [ ]:
find_largest_pop(area_one_pops,area_two_pops)

('Population Two is larger', [43845, 54930, 59354, 96403, 73492, 729320])

NumPY (NUMERICAL PYTHON)

In [2]:
# pip install is the package manager

import numpy as np

In [3]:
learn_array = np.array([1,2,3,4,5,6,7])

In [4]:
learn_array

array([1, 2, 3, 4, 5, 6, 7])

In [5]:
type(learn_array)

numpy.ndarray

In [6]:
example_array =[1,2,3,4]

In [7]:
example_array+3

TypeError: can only concatenate list (not "int") to list

In [8]:
example_array + [3]

[1, 2, 3, 4, 3]

In [9]:
numpy_arr = np.array(example_array)

In [13]:
numpy_arr + 60

array([61, 62, 63, 64])

In [14]:
length = np.array([9, 8,7,6,5,4])
width =np.array([9,8,7,6,5,4])


In [15]:
area = length * width
area

array([81, 64, 49, 36, 25, 16])

In [16]:
import time

# Using 1 million integers
huge_list_of_integers = list(range(0, 1000000))
huge_np_array_of_integers = np.array(huge_list_of_integers)

def add_one(list_of_ints):
    return [num + 1 for num in list_of_ints]


start_time = time.perf_counter() # Time when operation starts
add_one(huge_list_of_integers) # Adds 1 to each number in the list of integers above
end_time = time.perf_counter() # Time when operation finishes
total_time = (end_time - start_time) # Total time for operation
start_time_with_np = time.perf_counter() # Time when operation starts
huge_np_array_of_integers + 1 # Adds 1 to each number in the array of integers
end_time_with_np = time.perf_counter() # Time when operation finishes
total_time_with_np = (end_time_with_np - start_time_with_np) # Total time for operation

print('Time it takes to add 1 to each element in a list without NumPy:', total_time)
print('Time it takes to add 1 to each element in a list with NumPy:', total_time_with_np)

percent_faster = int((((total_time - total_time_with_np)/total_time)*100))
print('NumPy completes the operation', percent_faster, '% faster than a traditional list')

Time it takes to add 1 to each element in a list without NumPy: 0.1439385180001409
Time it takes to add 1 to each element in a list with NumPy: 0.0055845730003056815
NumPy completes the operation 96 % faster than a traditional list
