<a href="https://colab.research.google.com/github/warigiasue89/Refresher/blob/master/Refresher.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

In [4]:
import numpy as np
import matplotlib.pyplot as plt

In [5]:
learning = list(['orange','pineapple','mango'])
learning

['orange', 'pineapple', 'mango']

In [6]:
iteration = 2
for i in learning:
  iteration +=2
  print('iteration number:', iteration)
  print (i)
print ('is not in the for loop')

iteration number: 4
orange
iteration number: 6
pineapple
iteration number: 8
mango
is not in the for loop


In [7]:
for fruits in learning:
  print (fruits)

orange
pineapple
mango


In [8]:
countries= ['Crotia', 'USA', 'Argentina', 'France', 'Brazil', 'Japan','Vietnam']
countries

['Crotia', 'USA', 'Argentina', 'France', 'Brazil', 'Japan', 'Vietnam']

In [9]:
for index in range(len(countries)):
  print(index)
  print(countries[index])

0
Crotia
1
USA
2
Argentina
3
France
4
Brazil
5
Japan
6
Vietnam


In [10]:
countries= ['Crotia', 'USA', 'Argentina', 'France', 'Brazil', 'Japan','Vietnam']
cities = ['Zagreb', 'District of Columbia', 'Buenos Aires', 'Paris', 'Rio de Janeiro', 'Tokyo', 'Hanoi']

In [11]:
for index in range(len(countries)):
  print(cities[index],",", countries[index])

Zagreb , Crotia
District of Columbia , USA
Buenos Aires , Argentina
Paris , France
Rio de Janeiro , Brazil
Tokyo , Japan
Hanoi , Vietnam


In [12]:
# for index in range(8):
#    print(cities[index],",", countries[index])

In [13]:
range(len(countries))

range(0, 7)

In [14]:
list (range(len(countries)))

[0, 1, 2, 3, 4, 5, 6]

In [15]:
for index in list(range(len(countries))):
  print(cities[index],",",countries[index])


Zagreb , Crotia
District of Columbia , USA
Buenos Aires , Argentina
Paris , France
Rio de Janeiro , Brazil
Tokyo , Japan
Hanoi , Vietnam


In [16]:
countries.append ('Kenya')
cities.append ('Nairobi')
for index in list(range(len(countries))):
  print(cities[index],",",countries[index])

Zagreb , Crotia
District of Columbia , USA
Buenos Aires , Argentina
Paris , France
Rio de Janeiro , Brazil
Tokyo , Japan
Hanoi , Vietnam
Nairobi , Kenya


In [17]:
countries.reverse()


In [18]:
countries

['Kenya', 'Vietnam', 'Japan', 'Brazil', 'France', 'Argentina', 'USA', 'Crotia']

In [19]:
different_elements = ['Susan', ['shopping', 10, 'Saturday'],{'This is the key': '10'}]
different_elements

['Susan', ['shopping', 10, 'Saturday'], {'This is the key': '10'}]

In [20]:
for element in different_elements:
  print(element)

Susan
['shopping', 10, 'Saturday']
{'This is the key': '10'}


In [21]:
example_of_dictionary = {'first_name': 'mia', 'last_name':'Kebaso','age':27}
example_of_dictionary

{'first_name': 'mia', 'last_name': 'Kebaso', 'age': 27}

In [22]:
example_of_dictionary.items()

dict_items([('first_name', 'mia'), ('last_name', 'Kebaso'), ('age', 27)])

In [23]:
example_of_dictionary.keys()

dict_keys(['first_name', 'last_name', 'age'])

In [24]:
example_of_dictionary.values()

dict_values(['mia', 'Kebaso', 27])

In [25]:
for key, value in example_of_dictionary.items():
  print('this is the key:',key)
  print('this is the value:', value,'\n')

this is the key: first_name
this is the value: mia 

this is the key: last_name
this is the value: Kebaso 

this is the key: age
this is the value: 27 



In [26]:
# last_name =''
# first_name = ''
for key,value in example_of_dictionary.items():
  if key == 'first_name':
    first_name = value.upper()
  if key == 'last_name':
    last_name = value.lower()
print(first_name, last_name)


MIA kebaso


WHILE LOOPS

How to continue and break the loop

In [27]:
water_cans = 10
cans_carried= 0

for water_can in range(water_cans):
  print('We have carried')
  cans_carried +=1
  print(f'{cans_carried} can')
  # print(cans_carried)
  # print(cans_carried,'cans so far')


We have carried
1 can
We have carried
2 can
We have carried
3 can
We have carried
4 can
We have carried
5 can
We have carried
6 can
We have carried
7 can
We have carried
8 can
We have carried
9 can
We have carried
10 can


FUNCTIONS

In [28]:
def greet_people():
  print('Habari')

In [29]:
greet_people()

Habari


In [30]:
def calc (a,b):
  return(a*b)

In [31]:
calc(2,5)

10

In [32]:
new_interns = ['Kelly', 'Fiona' , 'Susan']


In [33]:
# def greet_people(name):
#   print('Habari', name)

In [34]:
# Defining a  function
def greet_people():
  welcome_message= []
  for name in new_interns:
    welcome_message.append('Habari' ' ' + name)
  return welcome_message

In [35]:
#Executing the function
greet_people()

['Habari Kelly', 'Habari Fiona', 'Habari Susan']

In [36]:
travel_destination = ['argentina', 'mexico', 'italy', 'finland', 'canada', 'croatia']


In [37]:
def number_of_destination():
  return len(travel_destination)

In [38]:
number_of_destination()

6

In [39]:
def next_up():
  return travel_destination[0]

In [40]:
next_up()

'argentina'

In [41]:
def favourite_destination():
  return('Madagascar')

In [42]:
favourite_destination()

'Madagascar'

In [43]:
def add_favourite_destination ():
  travel_destination.append(favourite_destination())
  return travel_destination[-1]

In [44]:
add_favourite_destination()

'Madagascar'

In [45]:
def capitalize_countries():
  for index in range(len(travel_destination)):
    travel_destination[index] = travel_destination[index].capitalize()
  return travel_destination

In [46]:
capitalize_countries()

['Argentina', 'Mexico', 'Italy', 'Finland', 'Canada', 'Croatia', 'Madagascar']

In [47]:
def meet(name):
  print('Jina langu ni' + ' ' + name)

In [48]:
meet('Mylo')

Jina langu ni Mylo


In [49]:
def find_the_mean(list_of_numbers):
  n= len(list_of_numbers)
  summation = sum(list_of_numbers)
  mean = summation/n
  return mean


In [50]:
find_the_mean([1,2,3,4,5,6,7,8,9,10])

5.5

In [51]:
area_one_pops = [10453, 12383, 8034, 800835, 76434, 32394]
find_the_mean(area_one_pops)

156755.5

In [52]:
area_two_pops = [43845, 54930, 59354, 96403, 73492, 729320]
find_the_mean(area_two_pops)

176224.0

In [53]:
def find_largest_pop(area_one_pops,area_two_pops):
  mean_one = find_the_mean(area_one_pops)
def find_largest_pop(area_one_pops,area_two_pops):
  mean_one = find_the_mean(area_one_pops)
  mean_two = find_the_mean(area_two_pops)
  if mean_one > mean_two:
    return ('Population One is larger', area_one_pops)
  else:
    return ('Population Two is larger', area_two_pops)

In [54]:
find_largest_pop(area_one_pops,area_two_pops)

('Population Two is larger', [43845, 54930, 59354, 96403, 73492, 729320])

NumPY (NUMERICAL PYTHON)

In [55]:
# pip install is the package manager

import numpy as np

In [56]:
learn_array = np.array([1,2,3,4,5,6,7])

In [57]:
learn_array

array([1, 2, 3, 4, 5, 6, 7])

In [58]:
type(learn_array)

numpy.ndarray

In [59]:
example_array =[1,2,3,4]

In [60]:
example_array+3

TypeError: can only concatenate list (not "int") to list

In [61]:
example_array + [3]

[1, 2, 3, 4, 3]

In [62]:
numpy_arr = np.array(example_array)

In [63]:
numpy_arr + 60

array([61, 62, 63, 64])

In [64]:
length = np.array([9, 8,7,6,5,4])
width =np.array([9,8,7,6,5,4])


In [65]:
area = length * width
area

array([81, 64, 49, 36, 25, 16])

In [66]:
import time

# Using 1 million integers
huge_list_of_integers = list(range(0, 1000000))
huge_np_array_of_integers = np.array(huge_list_of_integers)

def add_one(list_of_ints):
    return [num + 1 for num in list_of_ints]


start_time = time.perf_counter() # Time when operation starts
add_one(huge_list_of_integers) # Adds 1 to each number in the list of integers above
end_time = time.perf_counter() # Time when operation finishes
total_time = (end_time - start_time) # Total time for operation
start_time_with_np = time.perf_counter() # Time when operation starts
huge_np_array_of_integers + 1 # Adds 1 to each number in the array of integers
end_time_with_np = time.perf_counter() # Time when operation finishes
total_time_with_np = (end_time_with_np - start_time_with_np) # Total time for operation

print('Time it takes to add 1 to each element in a list without NumPy:', total_time)
print('Time it takes to add 1 to each element in a list with NumPy:', total_time_with_np)

percent_faster = int((((total_time - total_time_with_np)/total_time)*100))
print('NumPy completes the operation', percent_faster, '% faster than a traditional list')

Time it takes to add 1 to each element in a list without NumPy: 0.1090498249999996
Time it takes to add 1 to each element in a list with NumPy: 0.004712604999951964
NumPy completes the operation 95 % faster than a traditional list


**Getting started with Numerical Python**

In [67]:
x = [3,6,9]

In [69]:
x = np.array([3,6,9])
print(type(x))

<class 'numpy.ndarray'>


In [71]:
# List of numbers
x=[3,5,8,12,15,18,20,22,25,30,50,80,687]

In [72]:
x=sorted(x)

In [73]:
distance = len(x)-1
distance

12

In [74]:
index_p25 = 0.25 * distance
index_p25

3.0

In [75]:
index_p75 = 0.75 * distance
index_p75

9.0

In [78]:
p25 = x[int(index_p25)]
p25

12

In [79]:
p75 = x[int(index_p75)]
p75

30

In [82]:
iqr = p75 - p25
iqr

18

In [85]:
import numpy as np
np.percentile(x, 75) - np.percentile(x, 25)

18.0